### ISSUE TITLE
tolong bantuan nya

### ISSUE THREAD

**Issue by alvino-prog** [zifaucode/cek-lulus#4]
https://test.hizratech.com/
coba cek bg, saya sudah melakukan semua tapi masih error

**Comment by zifaucode** [comment]
sebelumnya sudah pernah hosting laravel ?

**Comment by alvino-prog** [comment]
Sebelum nya pernah, cuman di bantu sama orng berpengalaman nya kk, jadi
saya kurang mengerti

**Comment by zifaucode** [comment]
Boleh di perlihatkan errornya di bagian apanya mas
